- name: install rsyslog-gnutls
  apt:
    name: rsyslog-gnutls
    state: present
    force: yes

- name: modify certificates
  copy:
    src: papertrail-bundle.pem
    dest: /etc/papertrail-bundle.pem
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog

- name: copy rsyslog.conf
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog

- name: copy papertrail.conf
  template:
    src: papertrail.conf
    dest: /etc/rsyslog.d/papertrail.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog
