- name: install rsyslog-gnutls
  apt:
    name: rsyslog-gnutls
    state: latest
    force: yes

- name: modify certificates
  copy:
    src: papertrail-bundle.pem
    dest: /etc/papertrail-bundle.pem
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog

- name: modify rsyslog config
  template:
    src: 60-papertrail.conf
    dest: /etc/rsyslog.d/60-papertrail.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog
